### ISSUE TITLE
Submission: php7-http template

### ISSUE THREAD

**Issue by HeavyHorst** [openfaas/store#129]
I wrote an php7-http template that is based on https://github.com/spiral/roadrunner.
I took some ideas from the official php-template (php-extension.sh for installing extensions, composer.json etc.)

The template is located here: https://github.com/HeavyHorst/php-roadrunner-template.

The performance seems to be quite good (with the simple hello world example that returns the query parameters as json):

```
hey -n 5000 "http://localhost:8080?something=bla&one=1"
Summary:
  Total:	0.7239 secs
  Slowest:	0.0199 secs
  Fastest:	0.0008 secs
  Average:	0.0071 secs
  Requests/sec:	6906.9279
```

Would you accept a PR request for it?
